### DISCUSSION TITLE
How to setup multiple porfolios?

### DISCUSSION THREAD

**Discussion by CarlosGrohmann** [sylhare/Type-on-Strap#393] [Q&A] [answered]
Hi, I just started using the theme and I'm really enjoying it.

I'd like to know if it is possible to have multiple portfolios, based on different folders (I'm thinking that the gallery needs a gallery_path, could we have something like portfolio_path?

thanks

**Comment by sylhare** [comment, marked as answer]
You can have multiple portfolio, for that, you can create a new collection in the config.ym:
```
# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name
 other_portfolio:
    output: true
    permalink: /:collection/:name
```

Then you can follow the same folder structure as the `_portfolio` but with `_other_portfolio` as name to match the configuration.
