### ISSUE TITLE
Hamburger menu is not mobile friendly

### ISSUE THREAD

**Issue by wchen02** [sylhare/Type-on-Strap#184]
The default mobile hamburger menu has small font, are right aligned, and is very difficult to be tapped on.
![FireShot Capture 011 - Type on Strap - A website with blog posts and pages - sylhare github io](https://user-images.githubusercontent.com/197353/64326139-44e1fa00-cf7e-11e9-8480-2eba44c43bdf.png)

UI is very subjective, but it should be not impact user experience.
Here is my temporary solution added to main.scss:
```css
@media screen and (max-width: 768px) {
    .site-header nav ul li {
        text-align: center;
        font-size: 2em;
    }
}
```

![FireShot Capture 014 - Wensheng’s Blog - A software engineering blog - wenshengchen com](https://user-images.githubusercontent.com/197353/64326876-96d74f80-cf7f-11e9-885d-34014e1c85b9.png)
