### ISSUE TITLE
Type on Strap v2

### ISSUE THREAD

**Issue by sylhare** [sylhare/Type-on-Strap#187]
Preparation for the version 2 which will use Jekyll v4.0

**Comment by mhagnumdw** [comment]
Can you talk a bit about Type on Strap v2 and Jekyll v4.0? News, improvements etc

**Comment by sylhare** [comment]
Allo @mhagnumdw 

From Jekyll here what 4.0 brings:

> Ruby 2.4.0 or greater is now required.
> Rouge 3.0 or greater is now required for syntax highlighting.
> Jekyll builds should be much faster.
> Kramdown 2.1 is now the default markdown engine.
> Sass processing should be faster.
> Dropped support for a lot of stuff, specifically: (Pygments, RedCarpet, RDiscount)

There are also some changes in the liquid tags, so far on my tests, everything seems to be working fine.

I will also take on this opportunity to:
  - Rearrange `_config.yml` using the `_data` folder which might impact the user as some changes will need to occur on the user's side. 
 - Update jekyll plugins
 - Update the gemspec

**Comment by sylhare** [comment]
The new version is ready, should be merged into Master soon.
I have added some retro compatibility.

However a couple of adjustment need to be made regarding the theme settings:
```yaml
# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  avatar: assets/img/triangle.png
  color_image: /assets/img/lineart.png # In post when you set color
  favicon: assets/favicon.ico

  # Header and footer text
  header_text: Change header text in <code>_config.yml</code>
  header_feature_image: assets/img/pexels/triangular.jpeg
```

Will need to be transformed into:
```
# THEME-SPECIFIC CONFIGURATION
avatar: assets/img/triangle.png                         # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab
header_text:                                            # Change Blog header text
header_feature_image: assets/img/pexels/triangular.jpeg
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.
```

For the rest, it can coexist no problems, but for any customization, it will need to go through the new way (using `_data` and without the `theme_settings:` in the yaml).
