### ISSUE TITLE
Customization variable are not responding

### ISSUE THREAD

**Issue by sylhare** [sylhare/Type-on-Strap#269]
With the new dark mode enabled, this might have had an impact on your customization.

**Comment by sylhare** [comment]
With the new dark mode enabled, this might have had an impact on your customization.
If this is the case checkout the new [_variables.scss_](https://github.com/sylhare/Type-on-Strap/blob/master/_sass/base/_variables.scss) and 

Here is the **new format** of the customization for color variables for both dark and light:

```scss
html[data-theme="dark"] {
--background: #22272e; // brand, background
--blockquote: #373e47; // blockquote
--selection: #545d68; // selection
--meta: #909dab; // meta
--link: #00a8e0; // theme, link, link shadow header bg
--header-background: #2A3444; // Color before header image load
--header-text: #e7f3f4; // header text, feature img text
--header-link: #adbac7; // header link, search color
--code-background: #2A3444;
--code-inline: #d9b600;
--text-shadow: #2d333b; // text shadow
--text: #cdd9e5; // text
--h2: #d40059;
--h3: #ff66c2;
--h4: #00af9e;
--h5: #6bac00;
--border: rgba(0, 0, 0, 0.1); // border
}
```

And here are the variables that are now **deprecated**:

```scss
// Brand colours
$theme-color: #337ab7;
$brand-color: #fff;
$background-color: #fff;
$border-color: rgba(0, 0, 0, 0.1); // rgba recommended if using feature images

// Typography colours
$text-color: #262626;
$meta: #595959; //lowest gray for accessible color
$link-color: $theme-color;
$selection-color: #D4D4D4; // visible when highlighting text
$blockquote-color: #EEF7FA; // $background-color;

// Header
$header-background-color: darken($theme-color, 50%); // Only used when no header image
$header-text-color: #fff;
$header-link-color: #383838;
$navbar-separator-opacity: 0;

// Feature image for articles
$feature-image-text-color: #fff;
$feature-image-size: cover; // options include "cover", "contain", "auto"

//Search colours
$link-shadow: transparentize($link-color, .6); //rgba(26, 188, 156, 0.6);
$text-shadow: #3f3f3f;
$search-color: #999;
```
