### ISSUE TITLE
Responsive header_feature_image (optimized for mobile devices)?

### ISSUE THREAD

**Issue by musicmichaelc** [sylhare/Type-on-Strap#281]
I was wondering whether there is a way to make the `header_feature_image` display better on mobile devices. As of now, the image (which I sized to `2484x1280px` as recommended in the documentation) displays well on a desktop computer, but on a mobile phone, I can only see a small cut out section of the image.

Would it be possible to create several different image sizes&mdash;so as to serve the most optimal sizes depending on the device? Or is there already a way to do this that I might have missed?

**Comment by sylhare** [comment]
Maybe with something like:

```html
<img srcset="
  examples/images/image-384.jpg 1x, 
  examples/images/image-768.jpg 2x
" alt="…">
```

and 

```css
.img {
  background-image: url(examples/images/image-384.jpg); 
}
@media 
  (-webkit-min-device-pixel-ratio: 2), 
  (min-resolution: 192dpi) { 
  .img {
    background-image: url(examples/images/image-768.jpg);
  }
}
```
