### ISSUE TITLE
Portfolio link not ceated correctly?

### ISSUE THREAD

**Issue by CarlosGrohmann** [sylhare/Type-on-Strap#402]
Hi,

I'm testing a website and while running locally, everything is fine. But when I deploy to a test domain (a subdir in my own domain), the portfolio links don't work. 
You can see the test site here: http://carlosgrohmann.com/isg_test/
I can see in the statusbar that the links to the portfolio pages don't have the .html, unlike all the other pages and posts (if you add the .html at the end of the link, it works).
thanks

**Comment by CarlosGrohmann** [comment]
Ok, I found the answer. It turns out that in config.yml I had this:
```
# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name
```
so I changed the last line to 
`    permalink: /:collection/:name:output_ext`

All working fine now
