### ISSUE TITLE
"subtitle" field in post layout produces no result

### ISSUE THREAD

**Issue by CookiePLMonster** [Sylhare/Type-on-Strap#81]
As per docs:

```yml
layout: post
[...]
subtitle: "This is a subtitle"                    # A subtitle can be displayed below your title
```

However, using the field (both with and without quotations) produces no visible result. I thought it would produce the post summary instead of extracting it from the post body, but turns out `excerpt` does just that.

Should it produce any results for `post` layout or is it a leftover from `page` layout docs?
