### ISSUE TITLE
Numbered lists are formatted in an ugly way

### ISSUE THREAD

**Issue by CookiePLMonster** [Sylhare/Type-on-Strap#84]
By default, numbered lists are pretty ugly, they don't leave indentation under the index number, so text looks like this:

![image](https://user-images.githubusercontent.com/7947461/40254294-20d143c0-5ae3-11e8-8c8e-67b8b6c968e4.png)

Now, my suggestion is to indent text like this:
![image](https://user-images.githubusercontent.com/7947461/40254359-61700f60-5ae3-11e8-9e9e-333afef1235c.png)

To fix, change this in `_sass\base\global.scss` from:
```css
ol,
ul {
    list-style-position: inside;
}
```

to

```css
ol,
ul {
    list-style-position: outside;
    margin-left: 1em;
}
```
