### ISSUE TITLE
Highlighting inline code block

### ISSUE THREAD

**Issue by ryanking13** [Sylhare/Type-on-Strap#92]
It seems there is no highlight configuration for `inline code blocks` (#66 also asked this)

![image](https://user-images.githubusercontent.com/24893111/40931699-f6fbc5a2-6866-11e8-9947-f563074ef765.png)

(captured on [here](https://sylhare.github.io/Type-on-Strap/2014/08/08/Markup-Syntax-Highlighting.html))

I think it would be great if there is a highlight for this.

The image below is how I added a highlight on my fork ( imitated Github flavored markdown ) 

![image](https://user-images.githubusercontent.com/24893111/40931781-4729ae36-6867-11e8-8d1f-ba124d6e8ce6.png)

on [_sass/external/_syntax.scss](https://github.com/Sylhare/Type-on-Strap/blob/master/_sass/external/_syntax.scss) I added the code below.

```scss
code.highlighter-rouge {
    padding: 0.2em 0.4em;
    font-size: 85%;
    background-color: rgba(27,31,35,0.10);
    border-radius: 3px;
    font-family: 'Consolas';
}
```

(Sorry, I'm not familiar with css)
